import InputManager from "./core/inputManager.js";
import Player from "./entities/player.js";
import Bullet from "./entities/bullet.js";
import AudioManager from "./core/audio.js";
import Explosion from "./effects/explosion.js";
import ScoreManager from "./core/scoreManager.js";
import Item from "./entities/item.js";
import EnemyManager from "./managers/enemyManager.js";
import BossManager from "./managers/bossManager.js";

class Game {
  constructor() {
    this.titleScreen = document.getElementById("titleScreen"); this.gameContainer = document.getElementById("gameContainer"); this.gameOver = document.getElementById("gameOver"); this.stageClear = document.getElementById("stageClear"); this.canvas = document.getElementById("gameCanvas"); this.ctx = this.canvas.getContext("2d");
    this.ui = { score: document.getElementById("score"), life: document.getElementById("life"), stage: document.getElementById("stage"), highScore: document.getElementById("highScoreValue"), bossHp: document.getElementById("bossHp"), bossGauge: document.getElementById("bossGauge"), combo: document.getElementById("combo"), comboCount: document.getElementById("comboCount"), effects: document.getElementById("statusEffects"), itemTimer: document.getElementById("itemTimer"), powerTimer: document.getElementById("powerTimer"), shieldTimer: document.getElementById("shieldTimer"), pause: document.getElementById("pauseOverlay"), warning: document.getElementById("warningOverlay"), clearScore: document.getElementById("clearScore"), clearTitle: document.getElementById("stageClearTitle"), clearResults: document.getElementById("clearResults"), overResults: document.getElementById("gameOverResults"), next: document.getElementById("nextStageButton"), finalScore: document.getElementById("finalScore") };
    this.resizeCanvas(); this.input = new InputManager(this.canvas, [document.getElementById("leftStick"), document.getElementById("rightStick")]); this.player = new Player(this.canvas, this.input); this.audio = new AudioManager(); this.scoreManager = new ScoreManager(); this.enemyManager = new EnemyManager(this.canvas); this.bossManager = new BossManager(this.canvas); this.createStars(); this.running = false; this.paused = false; this.bindEvents(); this.updateHighScore();
  }
  bindEvents() { document.getElementById("startButton").addEventListener("click", () => this.start()); document.getElementById("retryButton").addEventListener("click", () => this.start()); document.getElementById("titleButton").addEventListener("click", () => this.backToTitle()); document.getElementById("nextStageButton").addEventListener("click", () => this.nextStage()); document.getElementById("clearTitleButton").addEventListener("click", () => this.backToTitle()); document.getElementById("pauseButton").addEventListener("click", () => this.togglePause()); document.getElementById("resumeButton").addEventListener("click", () => { if (this.paused) this.togglePause(); }); document.getElementById("rankingButton").addEventListener("click", () => this.showRanking()); document.getElementById("rankingBackButton").addEventListener("click", () => document.getElementById("rankingScreen").classList.add("hidden")); window.addEventListener("keydown", event => { if (event.key.toLowerCase() === "p" && this.running) this.togglePause(); }); window.addEventListener("resize", () => this.createStars()); document.addEventListener("visibilitychange", () => { if (document.hidden && this.running && !this.paused) this.togglePause(); }); }
  resizeCanvas() { this.canvas.width = 480; this.canvas.height = 800; }
  createStars() { this.stars = Array.from({ length: 95 }, () => ({ x: Math.random() * this.canvas.width, y: Math.random() * this.canvas.height, size: Math.random() * 1.8 + .4, speed: Math.random() * 100 + 25, alpha: Math.random() * .7 + .25 })); }
  resetGame() { this.score = 0; this.life = 3; this.stage = 1; this.combo = 0; this.maxCombo = 0; this.comboTimer = 0; this.elapsedTime = 0; this.hitStop = 0; this.shakeTime = 0; this.bossDefeatTimer = 0; this.shootTimer = 0; this.bullets = []; this.enemyBullets = []; this.explosions = []; this.items = []; this.enemyManager.reset(this.stage); this.bossManager.reset(); this.invincible = false; this.invincibleTimer = 0; this.player.powerLevel = 1; this.player.powerTimer = 0; this.player.weaponMode = null; this.player.weaponTimer = 0; this.player.shieldTimer = 0; this.player.resetPosition(); this.ui.next.classList.remove("hidden"); this.ui.clearTitle.textContent = "STAGE CLEAR"; this.ui.warning.classList.add("hidden"); this.stageClear.classList.remove("gameClear"); this.hideBossGauge(); this.showStageBanner(); this.updateHud(); }
  start() { this.titleScreen.classList.add("hidden"); this.gameOver.classList.add("hidden"); this.stageClear.classList.add("hidden"); this.gameContainer.classList.remove("hidden"); this.resetGame(); this.running = true; this.paused = false; this.lastTime = performance.now(); this.audio.playBGM(); requestAnimationFrame(time => this.loop(time)); }
  loop(time) { if (!this.running) return; const delta = Math.min((time - this.lastTime) / 1000, .05); this.lastTime = time; if (!this.paused) this.update(delta); this.render(time); requestAnimationFrame(t => this.loop(t)); }
  update(delta) {
    this.updateStars(delta); if (this.hitStop > 0) { this.hitStop -= delta; return; } if (this.bossDefeatTimer > 0) { this.bossDefeatTimer -= delta; this.explosions.forEach(effect => effect.update(delta * .35)); if (this.bossDefeatTimer <= 0) this.finishStage(); return; } this.elapsedTime += delta; if (this.shakeTime > 0) this.shakeTime -= delta; this.player.update(delta);
    if (this.bossManager.warningActive) { this.bossManager.warningTimer -= delta; if (!this.bossManager.warningActive) this.ui.warning.classList.add("hidden"); }
    if (this.invincible && (this.invincibleTimer -= delta) <= 0) this.invincible = false; if (this.comboTimer > 0 && (this.comboTimer -= delta) <= 0) this.combo = 0;
    this.shootTimer += delta; if (this.shootTimer >= .19) { this.shootTimer = 0; this.player.getShootPositions().forEach(pos => this.bullets.push(new Bullet(pos.x, pos.y, { type: pos.type, angle: pos.angle, getTargets: () => [...this.enemyManager.enemies, this.bossManager.boss].filter(Boolean) }))); this.audio.shoot(); }
    this.enemyBullets.push(...this.enemyManager.update(delta, this.player, this.bossManager.active)); if (this.bossManager.active && !this.bossManager.warningActive) this.enemyBullets.push(...this.bossManager.update(delta, this.player)); this.updateBossGauge(); [...this.bullets, ...this.enemyBullets, ...this.items, ...this.explosions].forEach(object => object.update(delta)); this.handleCollisions(); this.cleanup(); this.updateHud();
  }
  updateStars(delta) { this.stars.forEach(star => { star.y += star.speed * delta; if (star.y > this.canvas.height + 2) { star.y = -2; star.x = Math.random() * this.canvas.width; } }); }
  handleCollisions() { for (const enemy of this.enemyManager.enemies) for (const bullet of this.bullets) if (enemy.alive && bullet.alive && this.isHit(enemy, bullet)) { enemy.alive = false; bullet.alive = false; this.destroyEnemy(enemy); break; } if (this.bossManager.active) this.bullets.forEach(bullet => { if (bullet.alive && this.isHit(this.bossManager.boss, bullet)) this.bossManager.hit(bullet); }); const boss = this.bossManager.consumeDefeated(); if (boss) { this.score += 5000; this.hitStop = .28; this.shakeTime = .8; this.explosions.push(new Explosion(boss.x + boss.width / 2, boss.y + boss.height / 2, 5)); this.audio.explosion(); this.hideBossGauge(); this.bossDefeatTimer = .75; return; } this.items.forEach(item => { if (item.alive && this.isHit(this.player, item)) this.collectItem(item); }); if (!this.invincible && [...this.enemyManager.enemies, ...this.enemyBullets].some(object => this.isHit(this.player, object))) this.takeDamage(); }
  destroyEnemy(enemy) { this.score += 100 + Math.min(this.combo, 20) * 10; this.combo++; this.maxCombo = Math.max(this.maxCombo, this.combo); this.comboTimer = 2.2; this.hitStop = .045; this.shakeTime = .11; this.explosions.push(new Explosion(enemy.x + enemy.width / 2, enemy.y + enemy.height / 2)); this.audio.explosion(); if (Math.random() < .13) this.items.push(new Item(enemy.x + 4, enemy.y, this.getItemType())); if (this.enemyManager.registerKill() && !this.bossManager.active) { this.bossManager.spawn(this.stage); document.getElementById("bossTitle").textContent = `${this.bossManager.boss.name} // HP`; this.ui.warning.classList.remove("hidden"); this.showBossGauge(); } }
  collectItem(item) { item.alive = false; this.audio.item(); if (item.type === "heal") this.life = Math.min(3, this.life + 1); if (item.type === "power") this.player.powerUp(); if (item.type === "spread" || item.type === "missile") this.player.setWeapon(item.type); if (item.type === "shield") { this.invincible = true; this.invincibleTimer = 8; this.player.activateShield(); } }
  takeDamage() { this.life--; this.combo = 0; this.audio.hit(); this.invincible = true; this.invincibleTimer = 2.5; this.explosions.push(new Explosion(this.player.x + this.player.width / 2, this.player.y + this.player.height / 2)); if (this.life <= 0) this.gameOverTrigger(); }
  cleanup() { this.bullets = this.bullets.filter(x => x.alive); this.enemyBullets = this.enemyBullets.filter(x => x.alive); this.items = this.items.filter(x => x.alive); this.explosions = this.explosions.filter(x => x.alive); }
  drawBackground(ctx) { const gradient = ctx.createLinearGradient(0, 0, 0, this.canvas.height); if (this.stage === 1) { gradient.addColorStop(0, "#071a42"); gradient.addColorStop(.48, "#030a1c"); gradient.addColorStop(1, "#01030b"); ctx.fillStyle = gradient; ctx.fillRect(-8, -8, this.canvas.width + 16, this.canvas.height + 16); this.stars.forEach(star => { ctx.fillStyle = `rgba(195,232,255,${star.alpha})`; ctx.fillRect(star.x, star.y, star.size, star.size); }); return; } if (this.stage === 2) { gradient.addColorStop(0, "#111a2c"); gradient.addColorStop(.68, "#353b49"); gradient.addColorStop(1, "#14171f"); ctx.fillStyle = gradient; ctx.fillRect(-8, -8, this.canvas.width + 16, this.canvas.height + 16); ctx.fillStyle = "rgba(213,220,230,.16)"; [[90,160,42],[380,260,64],[150,520,76],[390,670,52]].forEach(([x,y,r]) => { ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2); ctx.fill(); }); return; } gradient.addColorStop(0, "#40170f"); gradient.addColorStop(.62, "#8e301a"); gradient.addColorStop(1, "#210b0b"); ctx.fillStyle = gradient; ctx.fillRect(-8, -8, this.canvas.width + 16, this.canvas.height + 16); ctx.fillStyle = "rgba(255,173,83,.18)"; ctx.beginPath(); ctx.arc(378,136,72,0,Math.PI*2); ctx.fill(); ctx.fillStyle = "rgba(37,8,7,.32)"; ctx.beginPath(); ctx.moveTo(0,590); ctx.quadraticCurveTo(135,510,260,620); ctx.quadraticCurveTo(350,690,480,565); ctx.lineTo(480,808); ctx.lineTo(0,808); ctx.fill(); }
  render(time) { const ctx = this.ctx; ctx.save(); if (this.shakeTime > 0) ctx.translate((Math.random() - .5) * 5, (Math.random() - .5) * 5); this.drawBackground(ctx); if (!this.invincible || Math.floor(time / 100) % 2 === 0) this.player.draw(ctx); this.bullets.forEach(x => x.draw(ctx)); this.enemyManager.enemies.forEach(x => x.draw(ctx)); this.enemyBullets.forEach(x => x.draw(ctx)); this.items.forEach(x => x.draw(ctx)); if (this.bossManager.active) this.bossManager.boss.draw(ctx); this.explosions.forEach(x => x.draw(ctx)); ctx.restore(); }
  getItemType() { const r = Math.random(); return r < .25 ? "heal" : r < .5 ? "power" : r < .67 ? "shield" : r < .84 ? "spread" : "missile"; }
  isHit(a, b) { const pad = 5; return !(a.x + a.width - pad < b.x + pad || a.x + pad > b.x + b.width - pad || a.y + a.height - pad < b.y + pad || a.y + pad > b.y + b.height - pad); }
  updateHud() { this.ui.score.textContent = this.score.toLocaleString(); this.ui.life.textContent = "◆".repeat(this.life) || "-"; this.ui.stage.textContent = this.stage; this.ui.comboCount.textContent = this.combo; this.ui.combo.classList.toggle("hidden", this.combo < 2); const nextItem = this.items.reduce((min, item) => Math.min(min, item.lifeTime), Infinity); this.ui.itemTimer.textContent = Number.isFinite(nextItem) ? `ITEM ${nextItem.toFixed(1)}s` : ""; this.ui.powerTimer.textContent = this.player.weaponTimer > 0 ? `${this.player.weaponMode.toUpperCase()} ${this.player.weaponTimer.toFixed(1)}s` : this.player.powerTimer > 0 ? `POWER ${this.player.powerTimer.toFixed(1)}s` : ""; this.ui.shieldTimer.textContent = this.player.shieldTimer > 0 ? `SHIELD ${this.player.shieldTimer.toFixed(1)}s` : ""; this.ui.effects.classList.toggle("hidden", !Number.isFinite(nextItem) && this.player.powerTimer <= 0 && this.player.weaponTimer <= 0 && this.player.shieldTimer <= 0); }
  updateHighScore() { this.ui.highScore.textContent = this.scoreManager.getHighScore().toLocaleString(); }
  showStageBanner() { const names = { 1: "DEEP SPACE", 2: "MOON BASE", 3: "MARS FRONTIER" }; const banner = document.getElementById("stageBanner"); document.getElementById("stageBannerNumber").textContent = `STAGE ${this.stage}`; document.getElementById("stageBannerName").textContent = names[this.stage]; banner.classList.remove("hidden"); banner.style.animation = "none"; void banner.offsetWidth; banner.style.animation = ""; setTimeout(() => banner.classList.add("hidden"), 1900); }
  showRanking() { const records = this.scoreManager.getRanking(); const list = document.getElementById("rankingList"); list.innerHTML = records.length ? records.map((record, index) => { const seconds = Math.floor(record.time || 0); const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; return `<div class="rankingRow"><strong>#${index + 1}</strong><strong>${record.score.toLocaleString()}</strong><span>STG ${record.stage}</span><span>${record.combo}C / ${time}</span></div>`; }).join("") : `<div class="rankingEmpty">NO RECORDS YET</div>`; document.getElementById("rankingScreen").classList.remove("hidden"); }
  showBossGauge() { this.ui.bossHp.classList.remove("hidden"); this.updateBossGauge(); } hideBossGauge() { this.ui.bossHp.classList.add("hidden"); }
  updateBossGauge() { if (this.bossManager.boss) this.ui.bossGauge.style.width = `${this.bossManager.boss.getHpRate() * 100}%`; }
  togglePause() { this.paused = !this.paused; this.ui.pause.classList.toggle("hidden", !this.paused); if (!this.paused) this.lastTime = performance.now(); }
  resultsMarkup() { const seconds = Math.floor(this.elapsedTime); const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; return `<span>PLAY TIME<strong>${time}</strong></span><span>MAX COMBO<strong>${this.maxCombo}</strong></span>`; }
  finishStage() { if (this.stage < 3) { this.advanceStage(); return; } this.running = false; this.audio.stopBGM(); this.scoreManager.saveRun({ score: this.score, stage: this.stage, combo: this.maxCombo, time: this.elapsedTime }); this.ui.clearScore.textContent = this.score.toLocaleString(); this.ui.clearTitle.textContent = "GAME CLEAR"; this.ui.clearResults.innerHTML = this.resultsMarkup(); this.stageClear.classList.add("gameClear"); this.ui.next.classList.add("hidden"); this.gameContainer.classList.add("hidden"); this.stageClear.classList.remove("hidden"); this.updateHighScore(); }
  advanceStage() { this.stage++; this.shootTimer = 0; this.bullets = []; this.enemyBullets = []; this.explosions = []; this.items = []; this.enemyManager.reset(this.stage); this.bossManager.reset(); this.ui.warning.classList.add("hidden"); this.hideBossGauge(); this.showStageBanner(); this.updateHud(); }
  nextStage() { this.advanceStage(); }
  gameOverTrigger() { this.running = false; this.audio.stopBGM(); this.scoreManager.saveRun({ score: this.score, stage: this.stage, combo: this.maxCombo, time: this.elapsedTime }); this.ui.finalScore.textContent = this.score.toLocaleString(); this.ui.overResults.innerHTML = this.resultsMarkup(); this.gameContainer.classList.add("hidden"); this.gameOver.classList.remove("hidden"); this.updateHighScore(); }
  backToTitle() { this.running = false; this.paused = false; this.ui.warning.classList.add("hidden"); this.stageClear.classList.remove("gameClear"); this.audio.stopBGM(); this.gameContainer.classList.add("hidden"); this.gameOver.classList.add("hidden"); this.stageClear.classList.add("hidden"); this.titleScreen.classList.remove("hidden"); this.hideBossGauge(); this.updateHighScore(); }
}
window.addEventListener("load", () => new Game());
